### ISSUE TITLE
What are the benefits of this extension in a TYPO3 composer mode instance?

### ISSUE THREAD

**Issue by josefglatz** [saschaende/typo3-aws#1]
I don't get the benefit just by reading why anyone use an additional extension which wraps just a composer dependency.

Cheers

**Comment by saschaende** [comment]
Thats not made for you. It’s made for me and my projects where I don’t use composer.

All my extensions are made for me, not for others.

Do you comment all extensions you don’t need? That’s a typical german behaviour.

**Comment by josefglatz** [comment]
Nope, that's a general question, because I generally scan extensions in extensions.typo3.org which are publicly available. Searching for useful extensions for my/future TYPO3  projects.

> This shouldn't be a personal attack on you 🙂

Beside of topics like what is best practice and so on for public TYPO3 extensions (at packagist and/or TER) it's important to understand that beginners in TYPO3 maybe decide to use an extension which is publicly available. And I was confused why to explain howto install this extension in composer mode - which is kind of a possible eye of a needle for a TYPO3 beginner using composer for his TYPO3 project who's asking himself "why should I not only require AWS SDK in my project composer.json". And as you already said, you use it in projects without composer. That can lead to misunderstandings... ¯\_(ツ)_/¯

I just want to draw your attention to the fact that you should look at it there. Each of us makes TYPO3. But if you don't want to get questions in your public TYPO3 extensions I try to mute myself when reading you extensions source code.

**Comment by saschaende** [comment]
Not every server has composer installed. On webspace packages without root access you never have composer.

Why do you think that everybody has Composer?

There are also cars with gas and Electric cars. That’s like asking the drivers with gas cars, why they need gas.

That’s really the most stupid and egoistic question I got since I am Programm TYPO3.

**Comment by saschaende** [comment]
Just to know: Until some years TYPO3 did not even have a composer mode. Most TYPO3 installations actually are NOT installed via composer.

**Comment by saschaende** [comment]
I leave this open for other people.

**Comment by josefglatz** [comment]
### composer on webserver

I use composer in 99,9% in my projects (and 100% in other non-typo3 PHP projects). In none of my webspace packages or servers is composer "installed/available". Beside that you can just upload composer.phar to you webspace if you want to run on your webserver.

### Why are you making the issue a general discussion?

My question was just about why to mention how to use this extension in TYPO3 composer mode. It totally makes no sense to me. I like to learn new things and therefore asked if there was any background to it.

Of course we can discuss that here too, but please keep objective.

#### so for others here

If you run TYPO3 in composer mode and you want to use the AWS SDK just require it in your project's composer.json: e.g. `composer require aws/aws-sdk-php:1.2.3`.

**Comment by saschaende** [comment]
By the way, I wouldn't be so mad if you hadn't been using TYPO3 for over 10 years.

So yes, it was a very stupid question, which mainly came from a TYPO3 professional - that's what makes it so annoying and unnecessary for us.
